<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>VietAIS.TCFlow.BuildingBlocks.EventSourcing</RootNamespace>
    <AssemblyName>VietAIS.TCFlow.BuildingBlocks.EventSourcing</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
</Project>
