<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>VietAIS.TCFlow.Modules.EventStorming.Tests</RootNamespace>
    <AssemblyName>VietAIS.TCFlow.Modules.EventStorming.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\EventStorming\Modules.EventStorming\Modules.EventStorming.csproj" />
    <ProjectReference Include="..\..\Modules\EventStorming\Modules.EventStorming.Contracts\Modules.EventStorming.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
